import Foundation

/// Build token for development mode device registration
///
/// ⚠️ THIS FILE IS AUTO-GENERATED DURING RELEASES
/// ⚠️ DO NOT MANUALLY EDIT THIS FILE
///
/// Generated: 2025-10-23 05:32:26 UTC
/// Release: Auto-generated by scripts/release_ios_sdk.sh
///
/// Security Model:
/// - This file is in .gitignore (not committed to main branch)
/// - Real tokens are ONLY in release tags (for SPM distribution)
/// - Token is used ONLY when SDK is in .development mode
/// - Backend validates token via POST /api/v1/devices/register/dev
///
/// Token Properties:
/// - Format: bt_<uuid>_<timestamp>
/// - Rotatable: Each release gets a new token
/// - Revocable: Backend can mark token as inactive
/// - Rate-limited: Backend enforces 100 req/min per device
enum BuildToken {
    /// Development mode build token
    /// Generated at: 2025-10-23 05:32:26 UTC
    static let token = "bt_2fc7892f-53e8-46df-9e93-319b98c81757_1761197540"
}
